### ISSUE TITLE
ModuleNotFoundError: No module named 'boilerpipe'

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/NwalaTextUtils#1]
**Environment**:

* Python 3.7.4
* macOS 10.14.6 (18G87)
* numpy 1.17.1
* scipy 1.3.1
* virtualenv
* ipython

**Issue**: 

After installing NwalaTextUtils, I tried to run the usage example form the README.md inside ipython and got a ModuleNotFoundError.

```
In [2]: from NwalaTextUtils.textutils import prlGetTxtFrmURIs
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-70df1e81a3a3> in <module>
----> 1 from NwalaTextUtils.textutils import prlGetTxtFrmURIs

~/.virtualenvs/nwala/lib/python3.7/site-packages/NwalaTextUtils/textutils.py in <module>
      4 import time
      5
----> 6 from boilerpipe.extract import Extractor
      7 from bs4 import BeautifulSoup
      8 from multiprocessing import Pool

ModuleNotFoundError: No module named 'boilerpipe'
```

A search on pypi.org shows 7 different boilerpipe Python libraries. I was uncertain as to which one I needed. I tried “pip install boilerpipe”, but that failed to install. I next tried “pip install boilerpipe3” and that installed fine. After that I was able to continue with the example and successfully produced a JSON file.

I have two suggestions to fix this:
* put the name of the correct boilerpipe library into setup.py
* if there are problems with doing that, put the name of the correct boilerpipe library into the README and note that this must be installed prior to use

**Comment by shawnmjones** [comment]
I just tried this using the official Python Docker image python:3.7.3-stretch and had the same problem. It does not appear to just be macOS or my specific configuration.

Docker environment for comparison:
* Python 3.7.3
* Linux 97ee5bc0586e 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
* numpy 1.17.1
* scipy 1.3.1
* system Python, not virtualenv
* ipython 7.7.0

My macOS environment is also running ipython 7.7.0.

**Comment by shawnmjones** [comment]
Pip seems to be ignoring the ``dependency_links`` section of setup.py.

https://github.com/oduwsdl/NwalaTextUtils/blob/523c79acc65ff0adaafc0b32b0ad705824c8e80c/setup.py#L28

According to https://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py it seems like `dependency_links` was deprecated in 2017 and is likely removed by now.

Running the install with `--process-dependency-links` within the Docker environment produces an error.

````
root@591d96c5d095:/# pip install NwalaTextUtils --process-dependency-links

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --process-dependency-links
````

**Comment by anwala** [comment]
Thanks for the suggestions. I've added a dependency section (see logfixes branch: https://github.com/oduwsdl/NwalaTextUtils/tree/logfixes) explicitly stating the boilerpipe libraries needed
