### ISSUE TITLE
raise_on_failure error in cleanHtml()

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/NwalaTextUtils#13]
In cleanHtml(), I was getting the error:
```
textutils.py, 308, (<class 'TypeError'>, TypeError("__init__() got an  unexpected 
keyword argument 'raise_on_failure'"), <traceback object at 0x147caba80>)
```
and no output from cleanHtml().

In my local version, I replaced 
```
extractor = extractors.ArticleExtractor(raise_on_failure=reportFailure)
```
with 
```
extractor = extractors.ArticleExtractor()
```
and things worked.  I'm not convinced that this isn't something related to my setup, but figured I'd log the issue anyway.

macOS 11.3
M1 processor
Python 3.9.1

**Comment by anwala** [comment]
Thanks @weiglemc for reporting this. 

I added that `raise_on_failure` at the recommendation of the developer:
https://github.com/jmriebold/BoilerPy3/pull/5

I'd investigate and reconsider if adding it's worth more trouble than good.

**Comment by anwala** [comment]
Hello @weiglemc, 

Very strange, I was not able to replicate this error by installing all current versions (1.0.1 -- 1.0.4) of boilerpy3 (https://pypi.org/project/boilerpy3/#history) inside a Python docker environment.

The [constructor](https://github.com/jmriebold/BoilerPy3/blob/master/boilerpy3/extractors.py#L146) of the `ArticleExtractor` class has the `raise_on_failure` parameter, so the error is unexpected.

**Comment by weiglemc** [comment]
It looks like the `raise_on_failure` parameter was added in 1.0.4 (https://raw.githubusercontent.com/jmriebold/BoilerPy3/master/CHANGELOG.md).  

I have 1.0.2 installed, and there's no such parameter in ArticleExtractor.py.

How can I install version 1.0.4?

**Comment by weiglemc** [comment]
When I installed boilerpy3 1.0.4, I got an error/warning that scraper 0.0.4 requires boilerpy3==1.0.2.  Maybe that setup just needs to be updated as >=1.0.2.  I'll post this issue in that repo.

**Comment by anwala** [comment]
Sorry, I didn't receive a notification about your update. I'll look into this again.

**Comment by anwala** [comment]
This problem has been [addressed](https://github.com/oduwsdl/NwalaTextUtils/commit/0d104e533a1c6b46dbddbfa98014fbc9d3406ed0) by asserting that `boilerpy3 >= 1.0.4`. 

I've updated [scraper](https://github.com/oduwsdl/scraper/commit/c6525bd205008dce1e365b71a895013577db032f), the [repo](https://github.com/oduwsdl/scraper/) is up to date, and would be reflected in scraper `v0.0.5`
