### ISSUE TITLE
"User-facing" functions need to be documented

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/NwalaTextUtils#3]
An example for using `cleanHtml`, `extractPageTitleFromHTML`, and other functions you wish the user to consume would be appreciated. I can guess what is intended by reading the code, but I shouldn’t have to read the code when starting out.

**Comment by anwala** [comment]
More documentation is in progress. See logfixes branch: https://github.com/oduwsdl/NwalaTextUtils/tree/logfixes
