### ISSUE TITLE
prlGetTxtFrmFiles?

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/NwalaTextUtils#4]
A function for using this against downloaded HTML files would be appreciated. I can write something myself and use `cleanHTML` and `extractPageTitleFromHTML`, but it would be nice if I could point a function at a folder and do the same thing as `prlGetTxtFrmURIs`, but for downloaded files instead. If you want, I can send you a pull request with some updated code.

**Comment by anwala** [comment]
Thanks for the suggestion. I've implemented and provided documentation for `prlGetTxtFrmFiles()`, which is similar to `prlGetTxtFrmURIs()` but processes a folder of HTML (would rm boilerplate) or Plaintext (would just return the text) files.

See logfixes branch: https://github.com/oduwsdl/NwalaTextUtils/tree/logfixes
