### ISSUE TITLE
Unexpected print statements

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/NwalaTextUtils#5]
It is unexpected for libraries to print out statements unless there is an error.

When I ran `prlGetTxtFrmURIs` I got unexpected output.

````
In [4]: doc_lst = prlGetTxtFrmURIs(uris_lst)
	deref uri i: 0 of 3
````

I can guess, but do not know what `deref uri i: 0 of 3` means. Such messages should be:

1. clearer
1. written out via a logging instead so that the user's screen and other interfaces are not clouded with this output - remember that your code will live with others code, and they will want to output their statements and may not care about yours

See: https://docs.python.org/3/howto/logging-cookbook.html

**Comment by shawnmjones** [comment]
To further illustrate my point, after I got the sumgram code working with oduwsdl/sumgram#1, I noticed the following in my output _before_ the sumgram output:

````
	deref uri i: 0 of 3

get_top_ngram():
	done adding sentences
	shift: 0

extract_top_ngrams(): token_pattern: (?u)\b[a-zA-Z\'\’-]+[a-zA-Z]+\b|\d+[.,]?\d*
/Users/smj/.virtualenvs/nwala/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['even'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
	top_ngrams.len: 1893
	doc_lst.len: 3
````

Which output comes from sumgram? Which output comes from NwalaTextUtils? I think I can tell which output comes from sklearn, but they did not do a good job either. They did, however, restrict their print statement for use with warnings, which is helpful.

**Comment by anwala** [comment]
Thanks for pointing this out. I've fixed this by implementing logging. So `prlGetTxtFrmURIs()` is quiet by default: https://github.com/oduwsdl/NwalaTextUtils/tree/logfixes
